/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Main {
    public static void main(String[] args) {
        Studente s1 = new Studente("Fra", "Piz", 130074);
        Studente s2 = new Studente("Tom", "Bas", 130075);

        Professore p1 = new Professore("Fab", "For", "Informatica");

        Corso c1 = new Corso("MDP", "For");

        s1.saluta();
        s2.saluta();
        p1.presenta();

        c1.iscriviStudente(s1);
        c1.iscriviStudente(s2);

        c1.stampaIscritti();

    }
}
