/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class Main {
    public static void main(String[] args) {
        Studente s1 = new Studente("Francesco", "Pizzi", 130074);
        Studente s2 = new Studente("Tommaso", "Basili", 130075);

        Professore p1 = new Professore("Fabrizio", "Fornari", "Informatica");

        Corso c1 = new Corso("MDP", "Fornari");

        Persona l1 = new Persona("Mario", "Rossi");

        s1.saluta();
        s2.saluta();
        p1.presenta();

        c1.iscriviStudente(s1);
        c1.iscriviStudente(s2);

        c1.stampaIscritti();

    }
}
